### ISSUE TITLE
Listening to 'iron-select' causes unexpected page animation

### ISSUE THREAD

**Issue by neolequang** [PolymerElements/neon-animation#146]
The fix for issue #112 causes unexpected pages animation because it listens for `iron-select` events.

When there is an element that fires an 'iron-select' event inside a page, then this event bubbles up to neon-animated page and cause an animation (using as the selected page the element that fired the `iron-select` event).

I wrote a sample jsbin, based on neon-animated-pages declarative demo : https://jsbin.com/romeyexuhi/edit?html,output

To reproduce to issue, go to the third page that contains a paper-listbox with paper-item elements, and select an item. You should see the page animating.

**Comment by manfield** [comment]
Alright. I think I just opened a similar issue.

**Comment by vguillou** [comment]
That's because of my fix to correct #112 .
I will be submitting a PR to correct that shortly.

**Comment by plequang** [comment]
Actually, if I understand it well, issue #112 is caused by https://github.com/PolymerElements/iron-selector/issues/95.

After reading the comments in this issue, the solution for #112 could be to observe changes to `selectedItem` instead of `selected`.

Something like: 
```
    observers: [
      '_selectedItemChanged(selectedItem)'
    ],

    _selectedItemChanged: function(selectedItem) {

      if (!selectedItem) {
        return;
      }
      var selectedPage = this.selectedItem;
      var oldPage = this._valueToItem(this._prevSelected) || false;
      this._prevSelected = this.selected;

      [...]
```

The ` if (!selectedItem) {` is needed because `iron-selection` set `selectedItem` to `undefined` before setting it to the new value (see https://github.com/PolymerElements/iron-selector/issues/27).

**Comment by jarrodek** [comment]
I have similar issues.

If you put `paper-checkbox` inside an element that is (somewhere in the DOM) enclosed in a `neon-animated-pages`, changing checkbox selection state will run entry animation in `neon-animated-pages`.

In my app I have a data table with checkboxes. Until yesterday it all worked as usual. However yesterday I did `bower update` on my project an everything crashed. After few hours I've discovered that if in my "table" element I add listener for `iron-deselect` and `iron-select` and in the listener I'll cancel the event like this:
```
e.preventDefault();
e.stopPropagation();
e.stopImmediatePropagation();
```
it is working as designed.

So the theory is that event is bubbling to the `neon-animated-pages` and it reacts on this event enabling animation.
It may, however, be related to changes in other elements. I've isolated following (updated) components that may be related to this issue:
* iron-selector
* iron-overlay-behavior

I'll start adding event cancellation to all my components that may influence the behaviour and I'll try to describe here any further findings.

**Comment by vguillou** [comment]
@jarrodek it very likely that your problem is the same as the one described in this issue report.
I would recommend you to fix the `neon-animated-pages` version in you `bower.json` file to `v1.1.0` to see if that resolves your problem.

If so, you can wait for a fix to land in this repo (there is already a PR #149 and @plequang's [proposal](https://github.com/PolymerElements/neon-animation/issues/146#issuecomment-194247109) waiting for review).

**Comment by jarrodek** [comment]
Thanks for clarifying @vguillou. I will.
