### ISSUE TITLE
Add a Polymer 3.0 branch (Polymer Modulizer)

### ISSUE THREAD

**Issue by MatxBerg** [PolymerElements/neon-animation#240]
I know this element is deprecated, but the 2.0 elements based on this element are still using it once converted to 3.0 elements. 

For example the 3.0 version of `<paper-menu-button>` has a dependency for:`"@polymer/neon-animation": "^3.0.0-pre.1"` which don't exist.

Could we have a modulized 3.0 version of neon-animation?

Thanks

**Comment by MajorBreakfast** [comment]
Jep, it's a real bummer that this branch doesn't exist. I really like Polymer 3.0, because JavaScript modules are way more flexible than HTML imports. Also, being able to use the same modules on the server and the client-side is very convenient. I've created a fork that makes neon animation work through some webpack configuration: https://www.npmjs.com/package/neon-animation-polymer-3

**Comment by MajorBreakfast** [comment]
Nice! And I see that it's also published to npm. This is great for Polymer 3 adoption.
