### ISSUE TITLE
'fade-out-animation' flickers on mobile web app

### ISSUE THREAD

**Issue by imskull** [PolymerElements/neon-animation#54]
When I played `fade-out-animation` on my android web app, the fading out page flickered at beginning, then it worked normally. This problem disappeared after I removed the `opaque-animation` hacky codes from 'neon-animated-pages.html' and 'neon-animatable-behavior.html'.

This problem only happened on my android web app(cordova + system webview), can't reproduce on my android chrome browser. my android version: 5.1.1, nexus 9.

**Comment by bflora2** [comment]
I am seeing the exact same problem as Imskull except only on fade-in-animation, not fade-out-animation. When dialog.open() is called the dialog appears instantly, disappears after maybe 100mS, then fades in normally.

The problem is sporadic, and occurs on Firefox, IE, and Edge, but never on Chrome (perhaps a race condition in the polyfill code?). The problem occurs most frequently on IE 11 and Edge.

**Comment by cdata** [comment]
Could you please re-open this bug with a reduced test case? Thanks!
