### ISSUE TITLE
Slide up/down animation does not work

### ISSUE THREAD

**Issue by LM450N** [PolymerElements/neon-animation#56]
Is it just me or the `slide-up-animation` and `slide-down-animation` are not working ? I don't know how to make them work. Is it possible to have an example of the configuration to provide in `animationConfig`?

Pleaaaaaase :smiley_cat:

**Comment by morethanreal** [comment]
Please post questions to StackOverflow (https://stackoverflow.com/questions/tagged/polymer) instead of filing an issue. The "load" and "tile" demos use `slide-up-animation` and `slide-down-animation` and they appear to be working. If you believe there is a bug, please re-open the issue with example code.

**Comment by LM450N** [comment]
Thanks and sorry to have opened an issue.
