### ISSUE TITLE
Orphaned neon-animating class causing page overlap.

### ISSUE THREAD

**Issue by shaunnetherby** [PolymerElements/neon-animation#71]
Changing the selected page before the current animation finishes causes the `neon-animating` class to remain on the `neon-animatable` being selected and the previously selected `neon-animatable`.  In my case, this is causing both pages to be opened and overlap each other.  This may be related to https://github.com/PolymerElements/neon-animation/issues/46.

I'm able to reproduce the orphaned `neon-animating` class in the 'declarative' demo for neon-animated-pages (although it doesn't seem to have an adverse effect in this case).  Here's a link to that demo: https://elements.polymer-project.org/elements/neon-animation?view=demo:demo/index.html&active=neon-animated-pages

To reproduce in the demo:

1) Click '>>' to transition to page 2
2) Click '<<' to transition to page 1 before the animation to page 2 completes.
3) Notice that both the `neon-animatable` for page 1 and 2 have the neon-animating class.

As a note, I only saw this problem after I updated to Chrome v45.

**Comment by hawkett** [comment]
I'm seeing this issue as well. In the demo mentioned above, I did notice an adverse effect - once the state becomes broken, moving between pages starts behaving erratically.

Before I realised this issue was already posted I put together a [jsbin for it](http://jsbin.com/nudufok/6/edit?html,console,output) - to reproduce:

1. Double-click the switch button
2. Click the switch button once more

**Correct Page 1**
![screen shot 2015-09-11 at 4 05 28 pm](https://cloud.githubusercontent.com/assets/134568/9828202/f6e104ae-589e-11e5-8cd2-8ce6533ece15.png)

**Correct Page 2**
![screen shot 2015-09-11 at 4 05 55 pm](https://cloud.githubusercontent.com/assets/134568/9828207/01c18736-589f-11e5-8d6c-9044d2d1e895.png)

**Broken Demo** 
![screen shot 2015-09-11 at 4 04 48 pm](https://cloud.githubusercontent.com/assets/134568/9828193/de2319fc-589e-11e5-8f6e-ac9a64eb9733.png)

**Comment by tommie** [comment]
Removing `this.squelchNextFinishEvent = true` seems to fix it. (Not saying that's the right solution, just giving a bit more debugging info.)

**Comment by ronnyroeller** [comment]
I'm observing the same issue.

**Comment by cdata** [comment]
Closing as fixed by #71.
